spring:
  application:
    name: cajalima

  docker:
    compose:
      enabled: false

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

server:
  port: ${BACKEND_PORT:8080}
